### ISSUE TITLE
PocketMine-MP version 3.3.2 support?

### ISSUE THREAD

**Issue by kfern** [hoyinm14mc/Jail#51]
Hello!

I would like to use this plugin but the API version is not compatible with version 3.3.2 of PocketMine-MP

Any plan to update? Can I help? I'm a PHP developer but a beginner minecraft developer.

[Server thread/INFO]: This server is running PocketMine-MP version 3.3.2
[Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[Server thread/INFO]: Loading resource packs...
[Server thread/ERROR]: Could not load plugin 'Jail': Incompatible API version (plugin requires one of: 2.0.0, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7)

**Comment by gordonmhy** [comment]
Regarding the fact that you have a background of programming, you may try doing this:
Manually editing the plugin.yml file and load Jail with DevTools.  In the plugin.yml file, you should edit the api version to the latest one so that it becomes compatible to the latest PocketMine version.
I'm not sure if doing this help since I have not been following the updates and changes of PocketMine itself so even if you successfully load the plugin, there might still be bugs or crashes.
